### ISSUE TITLE
 couldn't locate python interpreter

### ISSUE THREAD

**Issue by saranjsr** [ansible-community/ansible-bender#149] opened 2019-07-01 08:45 UTC
Hello,

I am using ansible-bender with AWS codebuild which is using Dockerfile ubuntu 18.04 as base image [gitHub](https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile). 
 I am getting below error. 

```
The following modules failed to execute: setup\n  setup: The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error
```
Complete log :
```
[Container] 2019/07/01 08:38:53 Running command ansible-bender --debug build --python-interpreter /usr/local/bin/python3 ./container.yml 
08:38:53.558 db.py             DEBUG  search for runtime dir 
08:38:53.558 db.py             DEBUG  trying ~/.cache 
08:38:53.558 db.py             DEBUG  runtime dir is /root/.cache 
08:38:53.559 core.py           DEBUG  this system is not using selinux, /sys/fs/selinux/enforce is not present 
08:38:53.562 core.py           DEBUG  ab vars key = ab_vars_20190701083853562720 
08:38:53.563 utils.py          INFO   running command: "['ansible-playbook', '--version']" 
08:38:53.563 utils.py          DEBUG  ansible-playbook --version 
08:38:53.838 utils.py          DEBUG  ansible-playbook 2.8.1 
08:38:53.838 utils.py          DEBUG    config file = /codebuild/output/src747764857/src/ubuntu/acs-container-images/ansible.cfg 
08:38:53.838 utils.py          DEBUG    configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'] 
08:38:53.838 utils.py          DEBUG    ansible python module location = /usr/local/lib/python3.7/site-packages/ansible 
08:38:53.838 utils.py          DEBUG    executable location = /usr/local/bin/ansible-playbook 
08:38:53.838 utils.py          DEBUG    python version = 3.7.3 (default, Jun 13 2019, 22:38:21) [GCC 7.4.0] 
08:38:53.859 utils.py          DEBUG  it seems that ansible-playbook is not using python 2 
08:38:53.859 core.py           DEBUG  ansible-playbook -c local -i /tmp/abit_lg536/i -e ansible_python_interpreter=/usr/local/bin/python3.7 ./.container-20190701083853562720-rsvatcxkwc.yaml 
08:38:53.859 utils.py          INFO   running command: "['ansible-playbook', '-c', 'local', '-i', '/tmp/abit_lg536/i', '-e', 'ansible_python_interpreter=/usr/local/bin/python3.7', './.container-20190701083853562720-rsvatcxkwc.yaml']" 
08:38:53.860 utils.py          DEBUG  ansible-playbook -c local -i /tmp/abit_lg536/i -e ansible_python_interpreter=/usr/local/bin/python3.7 ./.container-20190701083853562720-rsvatcxkwc.yaml 
08:38:54.522 utils.py          DEBUG   
08:38:54.522 utils.py          DEBUG  PLAY [Let Ansible expand variables] ******************************************** 
08:38:54.530 utils.py          DEBUG   
08:38:54.530 utils.py          DEBUG  TASK [debug] ******************************************************************* 
08:38:54.546 utils.py          DEBUG  ok: [localhost] => {} 
08:38:54.546 utils.py          DEBUG   
08:38:54.546 utils.py          DEBUG  MSG: 
08:38:54.546 utils.py          DEBUG   
08:38:54.546 utils.py          DEBUG  {'ansible_bender': {'base_image': 'ubuntu:16.04', 'working_container': {'volumes': ['/codebuild/output/src747764857/src/ubuntu/acs-container-images:/src']}, 'target_image': {'name': 'a-very-nice-image', 'working_dir': '/src', 'labels': {'built-by': 'root'}, 'environment': {'FILE_TO_PROCESS': 'README.md'}}}} 
08:38:54.550 utils.py          DEBUG   
08:38:54.550 utils.py          DEBUG  TASK [copy] ******************************************************************** 
08:38:55.125 utils.py          DEBUG  changed: [localhost] 
08:38:55.128 utils.py          DEBUG   
08:38:55.128 utils.py          DEBUG  PLAY RECAP ********************************************************************* 
08:38:55.128 utils.py          DEBUG  localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0    
08:38:55.128 utils.py          DEBUG   
08:38:55.174 utils.py          DEBUG  can't obtain user: 'user' 
08:38:55.174 utils.py          DEBUG  can't obtain cache_tasks: 'cache_tasks' 
08:38:55.174 utils.py          DEBUG  can't obtain layering: 'layering' 
08:38:55.174 utils.py          DEBUG  can't obtain ansible_extra_args: 'ansible_extra_args' 
08:38:55.174 utils.py          DEBUG  can't obtain verbose_layer_names: 'verbose_layer_names' 
08:38:55.179 db.py             DEBUG  initializing database 
08:38:55.180 buildah_builder.py DEBUG  checking that podman command works 
08:38:55.180 utils.py          INFO   running command: "['podman', 'version']" 
08:38:55.180 utils.py          DEBUG  podman version 
08:38:55.195 utils.py          DEBUG  Version:            1.4.3 
08:38:55.195 utils.py          DEBUG  RemoteAPI Version:  1 
08:38:55.195 utils.py          DEBUG  Go Version:         go1.10.4 
08:38:55.195 utils.py          DEBUG  OS/Arch:            linux/amd64 
08:38:55.196 buildah_builder.py DEBUG  checking that buildah command works 
08:38:55.196 utils.py          INFO   running command: "['buildah', 'version']" 
08:38:55.197 utils.py          DEBUG  buildah version 
08:38:55.223 utils.py          DEBUG  Version:         1.9.0-dev 
08:38:55.223 utils.py          DEBUG  Go Version:      go1.10.4 
08:38:55.223 utils.py          DEBUG  Image Spec:      1.0.0 
08:38:55.223 utils.py          DEBUG  Runtime Spec:    1.0.0 
08:38:55.223 utils.py          DEBUG  CNI Spec:        0.4.0 
08:38:55.223 utils.py          DEBUG  libcni Version:   
08:38:55.223 utils.py          DEBUG  Git Commit:       
08:38:55.223 utils.py          DEBUG  Built:           Thu May 30 23:39:16 2019 
08:38:55.224 utils.py          DEBUG  OS/Arch:         linux/amd64 
08:38:55.224 utils.py          INFO   running command: "['buildah', 'inspect', '-t', 'image', 'ubuntu:16.04']" 
08:38:55.224 utils.py          DEBUG  buildah inspect -t image ubuntu:16.04 
08:38:56.925 utils.py          ERROR  error reading image "ubuntu:16.04": error reading image: error locating image "ubuntu:16.04" for importing settings: error locating image with name "ubuntu:16.04" ([localhost/ubuntu:16.04 docker.io/library/ubuntu:16.04 registry.fedoraproject.org/ubuntu:16.04 quay.io/ubuntu:16.04 registry.access.redhat.com/ubuntu:16.04 registry.centos.org/ubuntu:16.04]): image not known 
08:38:56.926 buildah_builder.py INFO   pulling base image: ubuntu:16.04 
08:38:56.926 utils.py          INFO   running command: "['buildah', 'pull', 'ubuntu:16.04']" 
08:38:56.926 utils.py          DEBUG  buildah pull ubuntu:16.04 
08:38:59.081 utils.py          DEBUG  Getting image source signatures 
08:38:59.574 utils.py          DEBUG  Copying blob sha256:ad9c569a8d989555892683a932df468cfe294859186790d3f2fb704c3a022e96 
08:38:59.584 utils.py          DEBUG  Copying blob sha256:35b42117c431dd1e13679a09c3c68bb983578a1cbe0a8d8980f507567ebce76c 
08:38:59.596 utils.py          DEBUG  Copying blob sha256:0c175077525d1ddec01cb7cf003c2d8b4b6650ae15b504a64914f5eed8d28e50 
08:38:59.601 utils.py          DEBUG  Copying blob sha256:293b44f451623251bf75ce5a72d3cee63706972c88980232217a81026987f63e 
08:39:01.722 utils.py          DEBUG  Copying config sha256:13c9f1285025c03cfd56a2809973bfec93a6468953c4d0ed70afb1f492f50489 
08:39:02.082 utils.py          DEBUG  Writing manifest to image destination 
08:39:02.082 utils.py          DEBUG  Storing signatures 
08:39:04.522 buildah_builder.py DEBUG  trying to create a dummy container using podman 
08:39:04.522 utils.py          INFO   running command: "['podman', 'run', '--rm', 'ubuntu:16.04', 'true']" 
08:39:04.522 utils.py          DEBUG  podman run --rm ubuntu:16.04 true 
08:39:06.357 utils.py          INFO   running command: "['buildah', 'inspect', '-t', 'image', 'ubuntu:16.04']" 
08:39:06.357 utils.py          DEBUG  buildah inspect -t image ubuntu:16.04 
08:39:06.498 buildah_builder.py DEBUG  running command: from 
08:39:06.498 utils.py          INFO   running command: "['buildah', 'from', '-v', '/codebuild/output/src747764857/src/ubuntu/acs-container-images:/src', '--name', 'a-very-nice-image-20190701-083855179474-cont', '13c9f1285025c03cfd56a2809973bfec93a6468953c4d0ed70afb1f492f50489']" 
08:39:06.498 utils.py          DEBUG  buildah from -v /codebuild/output/src747764857/src/ubuntu/acs-container-images:/src --name a-very-nice-image-20190701-083855179474-cont 13c9f1285025c03cfd56a2809973bfec93a6468953c4d0ed70afb1f492f50489 
08:39:06.626 utils.py          DEBUG  a-very-nice-image-20190701-083855179474-cont 
08:39:06.653 buildah_builder.py DEBUG  running command: config 
08:39:06.653 utils.py          INFO   running command: "['buildah', 'config', '--workingdir', '/src', '-e', 'FILE_TO_PROCESS=README.md', '-l', 'built-by=root', 'a-very-nice-image-20190701-083855179474-cont']" 
08:39:06.654 utils.py          DEBUG  buildah config --workingdir /src -e FILE_TO_PROCESS=README.md -l built-by=root a-very-nice-image-20190701-083855179474-cont 
08:39:06.801 core.py           INFO   creating inventory file /tmp/abybj89coa/inventory 
08:39:06.805 core.py           DEBUG  play[0], host = all 
08:39:06.807 utils.py          INFO   running command: "['ansible-playbook', '--version']" 
08:39:06.807 utils.py          DEBUG  ansible-playbook --version 
08:39:07.077 utils.py          DEBUG  ansible-playbook 2.8.1 
08:39:07.078 utils.py          DEBUG    config file = /codebuild/output/src747764857/src/ubuntu/acs-container-images/ansible.cfg 
08:39:07.078 utils.py          DEBUG    configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'] 
08:39:07.078 utils.py          DEBUG    ansible python module location = /usr/local/lib/python3.7/site-packages/ansible 
08:39:07.078 utils.py          DEBUG    executable location = /usr/local/bin/ansible-playbook 
08:39:07.078 utils.py          DEBUG    python version = 3.7.3 (default, Jun 13 2019, 22:38:21) [GCC 7.4.0] 
08:39:07.098 utils.py          DEBUG  it seems that ansible-playbook is not using python 2 
08:39:07.098 core.py           DEBUG  ansible-playbook -c buildah -i /tmp/abybj89coa/inventory -vvv ./.container-20190701-083906807551-auwnvjuugl.yaml 
08:39:07.099 utils.py          INFO   running command: "['ansible-playbook', '-c', 'buildah', '-i', '/tmp/abybj89coa/inventory', '-vvv', './.container-20190701-083906807551-auwnvjuugl.yaml']" 
08:39:07.099 utils.py          DEBUG  ansible-playbook -c buildah -i /tmp/abybj89coa/inventory -vvv ./.container-20190701-083906807551-auwnvjuugl.yaml 
08:39:07.369 utils.py          DEBUG  ansible-playbook 2.8.1 
08:39:07.370 utils.py          DEBUG    config file = /tmp/abybj89coa/ansible.cfg 
08:39:07.370 utils.py          DEBUG    configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'] 
08:39:07.370 utils.py          DEBUG    ansible python module location = /usr/local/lib/python3.7/site-packages/ansible 
08:39:07.370 utils.py          DEBUG    executable location = /usr/local/bin/ansible-playbook 
08:39:07.370 utils.py          DEBUG    python version = 3.7.3 (default, Jun 13 2019, 22:38:21) [GCC 7.4.0] 
08:39:07.370 utils.py          DEBUG  Using /tmp/abybj89coa/ansible.cfg as config file 
08:39:07.381 utils.py          DEBUG  host_list declined parsing /tmp/abybj89coa/inventory as it did not pass it's verify_file() method 
08:39:07.381 utils.py          DEBUG  script declined parsing /tmp/abybj89coa/inventory as it did not pass it's verify_file() method 
08:39:07.381 utils.py          DEBUG  auto declined parsing /tmp/abybj89coa/inventory as it did not pass it's verify_file() method 
08:39:07.386 utils.py          DEBUG  Parsed /tmp/abybj89coa/inventory inventory source with ini plugin 
08:39:07.856 utils.py          DEBUG   
08:39:07.856 utils.py          DEBUG  PLAYBOOK: .container-20190701-083906807551-auwnvjuugl.yaml ********************* 
08:39:07.856 utils.py          DEBUG  1 plays in ./.container-20190701-083906807551-auwnvjuugl.yaml 
08:39:07.872 utils.py          DEBUG   
08:39:07.872 utils.py          DEBUG  PLAY [Demonstration of ansible-bender functionality] *************************** 
08:39:07.879 utils.py          DEBUG   
08:39:07.879 utils.py          DEBUG  TASK [Gathering Facts] ********************************************************* 
08:39:07.879 utils.py          DEBUG  task path: /codebuild/output/src747764857/src/ubuntu/acs-container-images/.container-20190701-083906807551-auwnvjuugl.yaml:1 
08:39:07.887 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> RUN [b'buildah', b'mount', b'--', b'a-very-nice-image-20190701-083855179474-cont'] 
08:39:08.008 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> RUN [b'buildah', b'run', b'--', b'a-very-nice-image-20190701-083855179474-cont', b'/bin/sh', b'-c', b'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1561970347.8868792-209580591521053 `" && echo ansible-tmp-1561970347.8868792-209580591521053="` echo /tmp/ansible-tmp-1561970347.8868792-209580591521053 `" ) && sleep 0'] 
08:39:08.695 utils.py          DEBUG  Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/system/setup.py 
08:39:08.696 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> PUT /root/.ansible/tmp/ansible-local-4407wjqit7w6/tmp7q84sziy TO /tmp/ansible-tmp-1561970347.8868792-209580591521053/AnsiballZ_setup.py 
08:39:08.696 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> RUN [b'buildah', b'run', b'--', b'a-very-nice-image-20190701-083855179474-cont', b'/bin/sh', b'-c', b'chmod u+x /tmp/ansible-tmp-1561970347.8868792-209580591521053/ /tmp/ansible-tmp-1561970347.8868792-209580591521053/AnsiballZ_setup.py && sleep 0'] 
08:39:09.128 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> RUN [b'buildah', b'run', b'--', b'a-very-nice-image-20190701-083855179474-cont', b'/bin/sh', b'-c', b'/usr/local/bin/python3 /tmp/ansible-tmp-1561970347.8868792-209580591521053/AnsiballZ_setup.py && sleep 0'] 
08:39:09.536 utils.py          DEBUG  <a-very-nice-image-20190701-083855179474-cont> RUN [b'buildah', b'umount', b'--', b'a-very-nice-image-20190701-083855179474-cont'] 
08:39:09.655 utils.py          DEBUG  fatal: [a-very-nice-image-20190701-083855179474-cont]: FAILED! => { 
08:39:09.655 utils.py          DEBUG      "ansible_facts": {}, 
08:39:09.655 utils.py          DEBUG      "changed": false, 
08:39:09.655 utils.py          DEBUG      "msg": "The following modules failed to execute: setup\n  setup: The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error\n" 
08:39:09.655 utils.py          DEBUG  } 
08:39:09.656 utils.py          DEBUG   
08:39:09.656 utils.py          DEBUG  PLAY RECAP ********************************************************************* 
08:39:09.656 utils.py          DEBUG  a-very-nice-image-20190701-083855179474-cont : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0    
08:39:09.656 utils.py          DEBUG   
08:39:09.714 buildah_builder.py DEBUG  running command: commit 
08:39:09.714 utils.py          INFO   running command: "['buildah', 'commit', 'a-very-nice-image-20190701-083855179474-cont', 'a-very-nice-image-failed']" 
08:39:09.714 utils.py          DEBUG  buildah commit a-very-nice-image-20190701-083855179474-cont a-very-nice-image-failed 
08:39:09.834 utils.py          DEBUG  Getting image source signatures 
08:39:09.834 utils.py          DEBUG  Copying blob sha256:1ea5a27b0484f2a227275fbb913d281461d9f356134a56002574904c3cfdea04 
08:39:09.834 utils.py          DEBUG  Copying blob sha256:24ab7de5faec98f9068e68257ce51c43cb98044a108e3f7f107e60bba3ad2ef4 
08:39:09.834 utils.py          DEBUG  Copying blob sha256:10e46f329a252698b52d88487165156ba4a52e5b62e75e10436e4353ae6ca687 
08:39:09.835 utils.py          DEBUG  Copying blob sha256:92d3f22d44f3a9ffaa7bbdf9d7ba902a66d39ab8d72e791b60b63a5b813ffa31 
08:39:09.835 utils.py          DEBUG  Copying blob sha256:2edc9016adf1c8f4ff300a53167ab918ff6fa70d8673f7996eea7b7eec334481 
08:39:10.194 utils.py          DEBUG  Copying config sha256:beaff2986c18b25ee4d8cfe744cc7e908546be618cc8609d9b8f238cf003f19b 
08:39:10.554 utils.py          DEBUG  Writing manifest to image destination 
08:39:10.554 utils.py          DEBUG  Storing signatures 
08:39:10.680 utils.py          DEBUG  beaff2986c18b25ee4d8cfe744cc7e908546be618cc8609d9b8f238cf003f19b 
08:39:10.681 utils.py          INFO   running command: "['buildah', 'inspect', '-t', 'image', 'a-very-nice-image-failed']" 
08:39:10.682 utils.py          DEBUG  buildah inspect -t image a-very-nice-image-failed 
08:39:10.800 buildah_builder.py DEBUG  running command: rm 
08:39:10.800 utils.py          INFO   running command: "['buildah', 'rm', 'a-very-nice-image-20190701-083855179474-cont']" 
08:39:10.801 utils.py          DEBUG  buildah rm a-very-nice-image-20190701-083855179474-cont 
08:39:10.956 utils.py          DEBUG  6ea15cd49c04451b72a9216fa8b5095a276c185018b2f4ccde806677d03fce4b 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/core.py", line 135, in run_playbook 
    log_stderr=log_stderr, 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/utils.py", line 112, in run_cmd 
    stderr=errout, output=out) 
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'buildah', '-i', '/tmp/abybj89coa/inventory', '-vvv', './.container-20190701-083906807551-auwnvjuugl.yaml']' returned non-zero exit status 2. 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/local/bin/ansible-bender", line 10, in <module> 
    sys.exit(main()) 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/cli.py", line 362, in main 
    sys.exit(CLI().run()) 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/cli.py", line 329, in run 
    self._build() 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/cli.py", line 284, in _build 
    self.app.build(build) 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/api.py", line 104, in build 
    output = a_runner.build(self.db_path) 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/core.py", line 225, in build 
    debug=self.debug, environment=environment, ansible_args=extra_args 
  File "/usr/local/lib/python3.7/site-packages/ansible_bender/core.py", line 138, in run_playbook 
    raise AbBuildUnsuccesful("ansible-playbook execution failed: %s" % ex, ex.output) 
ansible_bender.exceptions.AbBuildUnsuccesful: ansible-playbook execution failed: Command '['ansible-playbook', '-c', 'buildah', '-i', '/tmp/abybj89coa/inventory', '-vvv', './.container-20190701-083906807551-auwnvjuugl.yaml']' returned non-zero exit status 2. 
 
[Container] 2019/07/01 08:39:11 Command did not exit successfully ansible-bender --debug build --python-interpreter /usr/local/bin/python3 ./container.yml exit status 1 
```

I am passing --python-interpreter /usr/local/bin/python3  in my buildspec.yml. Please find attached buildspec-ubuntu.yml file.
```
I tried interpreter_python = /usr/local/bin/python3 in ansible.cfg file also and same I tried with simple-playbook.yaml with ansible_python_interpreter: /usr/local/bin/python3 but no luck.
```
There are no changes except base_image  ubuntu:16.04 instead of python:3-alpine.

**Comment by saranjsr** [comment] 2019-07-01 08:53
Hello,

sorry forgot to attach my buildpsspec-ubuntu.yml file.
```
version: 0.2

env:
  variables:
      AWS_DEFAULT_REGION: "eu-central-1"
      AWS_ACCOUNT_ID: "1234567"
      IMAGE_REPO_NAME: "container_imgfactory_ubuntu1604_linux"
      IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -qq
      - apt-get install -y git jq curl software-properties-common apt-utils uidmap iproute2 runc
      - curl https://omnitruck.chef.io/install.sh | bash -s -- -P inspec
      - pip3 install --force-reinstall pip==19.1.1
      - pip3 install docker==2.7.0
      - pip3 install ansible-bender
      - add-apt-repository -y ppa:projectatomic/ppa && apt-get update -qq && apt-get -qq -y install podman buildah
      - pip3 install ansible
      - git clone https://github.com/containers/conmon && cd conmon && make && make podman
      - apt autoremove -y

  pre_build:
    commands:
       - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
       - cd $CODEBUILD_SRC_DIR/ubuntu/acs-container-images
       - cp -av registries.conf libpod.conf /etc/containers/
       - export DATE=`date +%Y-%m-%d`
       - ansible-bender --debug build --python-interpreter /usr/local/bin/python3 ./container.yml
       - docker tag ubuntu1604-cis:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
       - docker tag ubuntu1604-cis:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DATE
       - docker images
```

**Comment by TomasTomecek** [comment] 2019-07-01 09:59
Well, I can't locate the interpreter myself:
```
$ podman run --rm -ti docker.io/ubuntu:18.04 sh                                                                                                                                  

# /usr/local/bin/python3
sh: 1: /usr/local/bin/python3: not found

# python3
sh: 2: python3: not found

# python
sh: 3: python: not found
```

**Comment by TomasTomecek** [comment] 2019-07-01 10:00
And you are talking about 18.04, but logs say `podman run --rm ubuntu:16.04 true`.

**Comment by saranjsr** [comment] 2019-07-01 10:14
I am using (https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/2.0/Dockerfile) Dockerfile. It has base image as ubuntu 18.04 and installed python3. 
I also build it with same Dockerfile on my local system. It has python3 in path /usr/local/bin/python3
```
root@f20d0791e90d:/# python3
Python 3.7.3 (default, Jun 28 2019, 20:42:05) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@f20d0791e90d:/# which python3
/usr/local/bin/python3
root@f20d0791e90d:/# which python3
/usr/local/bin/python3
root@f20d0791e90d:/# 

```

**Comment by TomasTomecek** [comment] 2019-07-01 10:24
Okay, so you want to use the aws image as a base, but instead you are using `ubuntu:16.04`:

```
'ansible_bender': {'base_image': 'ubuntu:16.04'
```

So please update your `./container.yml` and set the base image to the aws codebuild thing.

Closing since this is not a bender issue. Feel free to ask if you have more questions.

**Closed by TomasTomecek** 2019-07-01 10:24 UTC
Labels: invalid

**Comment by saranjsr** [comment] 2019-07-01 11:56
No. I want to use ubuntu 16.04 as base_image. AWS codebuild service is using ubuntu 18.04.

**Comment by TomasTomecek** [comment] 2019-07-01 12:11
I'm super lost right now. What are you actually trying to achieve?

**Comment by saranjsr** [comment] 2019-07-01 12:15
I want to build ubuntu 16.04 image and want to run CIS anisble playbooks in  ubuntu 16.04  container using AWS codebuild service.

**Comment by TomasTomecek** [comment] 2019-07-01 13:16
> I want to build ubuntu 16.04 image

This doesn't make any sense to me. ubuntu 16.04 images are available on docker hub, so why build it?

> and want to run CIS anisble playbooks

no idea what CIS is

> in ubuntu 16.04 container using AWS codebuild service.

I have never used AWS codebuild service. I heard about it first time this day.


So, if you want to get some assistance from me, please provide me a minimal reproducer which I can run locally on my laptop - I'd need the playbook you feed to `ansible-bender build`.

**Comment by saranjsr** [comment] 2019-07-02 10:56
[ansible-bender-sample.zip](https://github.com/ansible-community/ansible-bender/files/3349661/ansible-bender-sample.zip)

Attached folder(Dockerfile, conf files) which you can run on your local system.  I am building ubuntu 16.04  container and running ansible-bender inside container using below command.
```
docker build -t ansible-bender-test:v1 .
docker run -it --privileged -v /var/lib/containers/:/var/lib/containers/  ansible-bender-test:v1 /bin/bash
```
I am still getting  same error.
```
fatal: [a-very-nice-image-20190702-103840492701-cont]: FAILED! => {
10:39:26.826 utils.py          DEBUG      "ansible_facts": {},
10:39:26.826 utils.py          DEBUG      "changed": false,
10:39:26.826 utils.py          DEBUG      "msg": "The following modules failed to execute: setup\n  setup: The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error\n"
```
I am using your simple-playbook.yml. Only thing is I am using ubuntu:16.04 as base_image. I think ansible-bender should be able to run inside container.

**Comment by TomasTomecek** [comment] 2019-07-03 07:39
I downloaded your dockefile and it really scared me - I am not debugging that.

I tried the playbook locally, it's correct, it obviously failed on the same error I described above (no python interpreter).

This is the privileged container I am using to test bender: https://github.com/ansible-community/ansible-bender/blob/master/Makefile#L18

Sorry, can't help you.
