### ISSUE TITLE
Errors or not Errors?

### ISSUE THREAD

**Issue by mchassy** [ansible-community/ansible-bender#193] opened 2019-11-15 13:35 UTC
Here is the output of an ansible-bender command.
I see some errors, but everything seems to execute normally afterwards.
Are these actual errors?

```
$ echo "Gitlab Runner Stage $CI_JOB_STAGE"
Gitlab Runner Stage build_image
$ ansible-bender build  ./build/config.yml
13:31:07.211 utils.py          ERROR  Getting image source signatures
13:31:07.384 utils.py          ERROR  Copying blob sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609
13:31:07.422 utils.py          ERROR  Copying blob sha256:ccc4f7776013d50bdede808928179c682f9f369191aaa17c8f22e23fd9ea4507
13:31:08.532 utils.py          ERROR  Copying config sha256:6f49e00d5bfa34f3bd138d4ad28eb97c90f8c662f633540e9f80cabbb6c32451
13:31:08.892 utils.py          ERROR  Writing manifest to image destination
13:31:08.893 utils.py          ERROR  Storing signatures

PLAY [kudos] *******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [kudos-20191115-133106544341-cont]

TASK [Install additional packages] *********************************************
changed: [kudos-20191115-133106544341-cont]

TASK [Install dumb init] *******************************************************
ok: [kudos-20191115-133106544341-cont]

TASK [install the latest version of pip] ***************************************
changed: [kudos-20191115-133106544341-cont]

TASK [create /kudos directory] *************************************************
changed: [kudos-20191115-133106544341-cont]

TASK [copy in pip requirements] ************************************************
changed: [kudos-20191115-133106544341-cont]

TASK [install pip requirments] *************************************************
changed: [kudos-20191115-133106544341-cont]

TASK [create config directory] *************************************************
changed: [kudos-20191115-133106544341-cont]

TASK [create code directory] ***************************************************
changed: [kudos-20191115-133106544341-cont]

TASK [copy in entrypoint.sh] ***************************************************
changed: [kudos-20191115-133106544341-cont]

PLAY RECAP *********************************************************************
kudos-20191115-133106544341-cont : ok=10   changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

**Comment by TomasTomecek** [comment] 2019-11-19 14:19
Howdy!

The problem is that buildah prints informational output to stderr instead of stdout for sake of scripting. What you are seeing is normal output from buildah but bender thinks those are errors because they are written to stderr of the buildah process.

Okay, this can actually be fixed on our side easily, we just need to call buildah with the `--quiet` flag.

**Comment by mchassy** [comment] 2019-11-19 14:31
Thanks Tomas.

**Closed** 2019-11-20 08:27 UTC
Labels: UX, good first issue

**Comment by J-PC** [comment] 2024-09-12 15:05
It seem's the problem have been reintroduced or some other output leads to the same consequence.

![image](https://github.com/user-attachments/assets/d3fc7d3a-d5b5-486c-8512-e71bb0be58af)
