### ISSUE TITLE
No libselinux package found when using Python 3.8 (needed by Ansible Core 2.12)

### ISSUE THREAD

**Issue by TheMasterFX** [ansible-community/ansible-bender#275] opened 2022-07-09 22:05 UTC
I'm using AlmaLinux 8.6 and ansible-bender 0.9.0. If I install ansible it needs python 3.8 since it provides ansible-core-2.12.2. But there is no python38-libsselinux package for python 3.8, an according to this bugreport there never will be? ( https://bugzilla.redhat.com/show_bug.cgi?id=1932650 )
However I was not able to run ansible-bender since it is checking for selinux (_selinux) available
```
There was an error during execution:
This system is using selinux(8) and selinux python module is not installed. There is a known issue in ansible that it freezes in this setup:
  https://bugzilla.redhat.com/show_bug.cgi?id=1696706
Please install libselinux python bindings (on Fedora the package name is python3-libselinux).
```
So I just modified the function __check_selinux_iz_gud_ to just return. It seems to work. However I dont't know if it was just luck due to my minimalistic playbook.

**Comment by quietjoy** [comment] 2022-12-28 00:42
I ran into this as well on fedora. My workaround was installing the selinux shim via pip/pypi in my virtualenv. 

@TomasTomecek - in the bug report linked to in the error message shown, you advocated closing the bug report because, `Screw these heisenbugs: I can't reproduce the freeze anymore: tried a clean VM and my dirty workstation and the freeze happened on neither.` :)

I've opened #285 to address this.

**Closed** 2023-01-02 13:39 UTC
